// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: google/cloud/dialogflow/v2/answer_record.proto
// Original file comments:
// Copyright 2022 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#ifndef GRPC_google_2fcloud_2fdialogflow_2fv2_2fanswer_5frecord_2eproto__INCLUDED
#define GRPC_google_2fcloud_2fdialogflow_2fv2_2fanswer_5frecord_2eproto__INCLUDED

#include "google/cloud/dialogflow/v2/answer_record.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace google {
namespace cloud {
namespace dialogflow {
namespace v2 {

// Service for managing [AnswerRecords][google.cloud.dialogflow.v2.AnswerRecord].
class AnswerRecords final {
 public:
  static constexpr char const* service_full_name() {
    return "google.cloud.dialogflow.v2.AnswerRecords";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Returns the list of all answer records in the specified project in reverse
    // chronological order.
    virtual ::grpc::Status ListAnswerRecords(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::ListAnswerRecordsRequest& request, ::google::cloud::dialogflow::v2::ListAnswerRecordsResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2::ListAnswerRecordsResponse>> AsyncListAnswerRecords(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::ListAnswerRecordsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2::ListAnswerRecordsResponse>>(AsyncListAnswerRecordsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2::ListAnswerRecordsResponse>> PrepareAsyncListAnswerRecords(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::ListAnswerRecordsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2::ListAnswerRecordsResponse>>(PrepareAsyncListAnswerRecordsRaw(context, request, cq));
    }
    // Updates the specified answer record.
    virtual ::grpc::Status UpdateAnswerRecord(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::UpdateAnswerRecordRequest& request, ::google::cloud::dialogflow::v2::AnswerRecord* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2::AnswerRecord>> AsyncUpdateAnswerRecord(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::UpdateAnswerRecordRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2::AnswerRecord>>(AsyncUpdateAnswerRecordRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2::AnswerRecord>> PrepareAsyncUpdateAnswerRecord(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::UpdateAnswerRecordRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2::AnswerRecord>>(PrepareAsyncUpdateAnswerRecordRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // Returns the list of all answer records in the specified project in reverse
      // chronological order.
      virtual void ListAnswerRecords(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::ListAnswerRecordsRequest* request, ::google::cloud::dialogflow::v2::ListAnswerRecordsResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ListAnswerRecords(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::ListAnswerRecordsRequest* request, ::google::cloud::dialogflow::v2::ListAnswerRecordsResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Updates the specified answer record.
      virtual void UpdateAnswerRecord(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::UpdateAnswerRecordRequest* request, ::google::cloud::dialogflow::v2::AnswerRecord* response, std::function<void(::grpc::Status)>) = 0;
      virtual void UpdateAnswerRecord(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::UpdateAnswerRecordRequest* request, ::google::cloud::dialogflow::v2::AnswerRecord* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2::ListAnswerRecordsResponse>* AsyncListAnswerRecordsRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::ListAnswerRecordsRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2::ListAnswerRecordsResponse>* PrepareAsyncListAnswerRecordsRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::ListAnswerRecordsRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2::AnswerRecord>* AsyncUpdateAnswerRecordRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::UpdateAnswerRecordRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2::AnswerRecord>* PrepareAsyncUpdateAnswerRecordRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::UpdateAnswerRecordRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status ListAnswerRecords(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::ListAnswerRecordsRequest& request, ::google::cloud::dialogflow::v2::ListAnswerRecordsResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2::ListAnswerRecordsResponse>> AsyncListAnswerRecords(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::ListAnswerRecordsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2::ListAnswerRecordsResponse>>(AsyncListAnswerRecordsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2::ListAnswerRecordsResponse>> PrepareAsyncListAnswerRecords(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::ListAnswerRecordsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2::ListAnswerRecordsResponse>>(PrepareAsyncListAnswerRecordsRaw(context, request, cq));
    }
    ::grpc::Status UpdateAnswerRecord(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::UpdateAnswerRecordRequest& request, ::google::cloud::dialogflow::v2::AnswerRecord* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2::AnswerRecord>> AsyncUpdateAnswerRecord(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::UpdateAnswerRecordRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2::AnswerRecord>>(AsyncUpdateAnswerRecordRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2::AnswerRecord>> PrepareAsyncUpdateAnswerRecord(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::UpdateAnswerRecordRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2::AnswerRecord>>(PrepareAsyncUpdateAnswerRecordRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void ListAnswerRecords(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::ListAnswerRecordsRequest* request, ::google::cloud::dialogflow::v2::ListAnswerRecordsResponse* response, std::function<void(::grpc::Status)>) override;
      void ListAnswerRecords(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::ListAnswerRecordsRequest* request, ::google::cloud::dialogflow::v2::ListAnswerRecordsResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void UpdateAnswerRecord(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::UpdateAnswerRecordRequest* request, ::google::cloud::dialogflow::v2::AnswerRecord* response, std::function<void(::grpc::Status)>) override;
      void UpdateAnswerRecord(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::UpdateAnswerRecordRequest* request, ::google::cloud::dialogflow::v2::AnswerRecord* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2::ListAnswerRecordsResponse>* AsyncListAnswerRecordsRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::ListAnswerRecordsRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2::ListAnswerRecordsResponse>* PrepareAsyncListAnswerRecordsRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::ListAnswerRecordsRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2::AnswerRecord>* AsyncUpdateAnswerRecordRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::UpdateAnswerRecordRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2::AnswerRecord>* PrepareAsyncUpdateAnswerRecordRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::UpdateAnswerRecordRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_ListAnswerRecords_;
    const ::grpc::internal::RpcMethod rpcmethod_UpdateAnswerRecord_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Returns the list of all answer records in the specified project in reverse
    // chronological order.
    virtual ::grpc::Status ListAnswerRecords(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2::ListAnswerRecordsRequest* request, ::google::cloud::dialogflow::v2::ListAnswerRecordsResponse* response);
    // Updates the specified answer record.
    virtual ::grpc::Status UpdateAnswerRecord(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2::UpdateAnswerRecordRequest* request, ::google::cloud::dialogflow::v2::AnswerRecord* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_ListAnswerRecords : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ListAnswerRecords() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_ListAnswerRecords() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListAnswerRecords(::grpc::ServerContext* /*context*/, const ::google::cloud::dialogflow::v2::ListAnswerRecordsRequest* /*request*/, ::google::cloud::dialogflow::v2::ListAnswerRecordsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestListAnswerRecords(::grpc::ServerContext* context, ::google::cloud::dialogflow::v2::ListAnswerRecordsRequest* request, ::grpc::ServerAsyncResponseWriter< ::google::cloud::dialogflow::v2::ListAnswerRecordsResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_UpdateAnswerRecord : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_UpdateAnswerRecord() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_UpdateAnswerRecord() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateAnswerRecord(::grpc::ServerContext* /*context*/, const ::google::cloud::dialogflow::v2::UpdateAnswerRecordRequest* /*request*/, ::google::cloud::dialogflow::v2::AnswerRecord* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestUpdateAnswerRecord(::grpc::ServerContext* context, ::google::cloud::dialogflow::v2::UpdateAnswerRecordRequest* request, ::grpc::ServerAsyncResponseWriter< ::google::cloud::dialogflow::v2::AnswerRecord>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_ListAnswerRecords<WithAsyncMethod_UpdateAnswerRecord<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_ListAnswerRecords : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ListAnswerRecords() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::google::cloud::dialogflow::v2::ListAnswerRecordsRequest, ::google::cloud::dialogflow::v2::ListAnswerRecordsResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::google::cloud::dialogflow::v2::ListAnswerRecordsRequest* request, ::google::cloud::dialogflow::v2::ListAnswerRecordsResponse* response) { return this->ListAnswerRecords(context, request, response); }));}
    void SetMessageAllocatorFor_ListAnswerRecords(
        ::grpc::MessageAllocator< ::google::cloud::dialogflow::v2::ListAnswerRecordsRequest, ::google::cloud::dialogflow::v2::ListAnswerRecordsResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::google::cloud::dialogflow::v2::ListAnswerRecordsRequest, ::google::cloud::dialogflow::v2::ListAnswerRecordsResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ListAnswerRecords() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListAnswerRecords(::grpc::ServerContext* /*context*/, const ::google::cloud::dialogflow::v2::ListAnswerRecordsRequest* /*request*/, ::google::cloud::dialogflow::v2::ListAnswerRecordsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ListAnswerRecords(
      ::grpc::CallbackServerContext* /*context*/, const ::google::cloud::dialogflow::v2::ListAnswerRecordsRequest* /*request*/, ::google::cloud::dialogflow::v2::ListAnswerRecordsResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_UpdateAnswerRecord : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_UpdateAnswerRecord() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::google::cloud::dialogflow::v2::UpdateAnswerRecordRequest, ::google::cloud::dialogflow::v2::AnswerRecord>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::google::cloud::dialogflow::v2::UpdateAnswerRecordRequest* request, ::google::cloud::dialogflow::v2::AnswerRecord* response) { return this->UpdateAnswerRecord(context, request, response); }));}
    void SetMessageAllocatorFor_UpdateAnswerRecord(
        ::grpc::MessageAllocator< ::google::cloud::dialogflow::v2::UpdateAnswerRecordRequest, ::google::cloud::dialogflow::v2::AnswerRecord>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::google::cloud::dialogflow::v2::UpdateAnswerRecordRequest, ::google::cloud::dialogflow::v2::AnswerRecord>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_UpdateAnswerRecord() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateAnswerRecord(::grpc::ServerContext* /*context*/, const ::google::cloud::dialogflow::v2::UpdateAnswerRecordRequest* /*request*/, ::google::cloud::dialogflow::v2::AnswerRecord* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* UpdateAnswerRecord(
      ::grpc::CallbackServerContext* /*context*/, const ::google::cloud::dialogflow::v2::UpdateAnswerRecordRequest* /*request*/, ::google::cloud::dialogflow::v2::AnswerRecord* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_ListAnswerRecords<WithCallbackMethod_UpdateAnswerRecord<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_ListAnswerRecords : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ListAnswerRecords() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_ListAnswerRecords() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListAnswerRecords(::grpc::ServerContext* /*context*/, const ::google::cloud::dialogflow::v2::ListAnswerRecordsRequest* /*request*/, ::google::cloud::dialogflow::v2::ListAnswerRecordsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_UpdateAnswerRecord : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_UpdateAnswerRecord() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_UpdateAnswerRecord() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateAnswerRecord(::grpc::ServerContext* /*context*/, const ::google::cloud::dialogflow::v2::UpdateAnswerRecordRequest* /*request*/, ::google::cloud::dialogflow::v2::AnswerRecord* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_ListAnswerRecords : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ListAnswerRecords() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_ListAnswerRecords() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListAnswerRecords(::grpc::ServerContext* /*context*/, const ::google::cloud::dialogflow::v2::ListAnswerRecordsRequest* /*request*/, ::google::cloud::dialogflow::v2::ListAnswerRecordsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestListAnswerRecords(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_UpdateAnswerRecord : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_UpdateAnswerRecord() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_UpdateAnswerRecord() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateAnswerRecord(::grpc::ServerContext* /*context*/, const ::google::cloud::dialogflow::v2::UpdateAnswerRecordRequest* /*request*/, ::google::cloud::dialogflow::v2::AnswerRecord* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestUpdateAnswerRecord(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ListAnswerRecords : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ListAnswerRecords() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ListAnswerRecords(context, request, response); }));
    }
    ~WithRawCallbackMethod_ListAnswerRecords() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListAnswerRecords(::grpc::ServerContext* /*context*/, const ::google::cloud::dialogflow::v2::ListAnswerRecordsRequest* /*request*/, ::google::cloud::dialogflow::v2::ListAnswerRecordsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ListAnswerRecords(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_UpdateAnswerRecord : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_UpdateAnswerRecord() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->UpdateAnswerRecord(context, request, response); }));
    }
    ~WithRawCallbackMethod_UpdateAnswerRecord() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateAnswerRecord(::grpc::ServerContext* /*context*/, const ::google::cloud::dialogflow::v2::UpdateAnswerRecordRequest* /*request*/, ::google::cloud::dialogflow::v2::AnswerRecord* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* UpdateAnswerRecord(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ListAnswerRecords : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ListAnswerRecords() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::google::cloud::dialogflow::v2::ListAnswerRecordsRequest, ::google::cloud::dialogflow::v2::ListAnswerRecordsResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::google::cloud::dialogflow::v2::ListAnswerRecordsRequest, ::google::cloud::dialogflow::v2::ListAnswerRecordsResponse>* streamer) {
                       return this->StreamedListAnswerRecords(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ListAnswerRecords() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ListAnswerRecords(::grpc::ServerContext* /*context*/, const ::google::cloud::dialogflow::v2::ListAnswerRecordsRequest* /*request*/, ::google::cloud::dialogflow::v2::ListAnswerRecordsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedListAnswerRecords(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::google::cloud::dialogflow::v2::ListAnswerRecordsRequest,::google::cloud::dialogflow::v2::ListAnswerRecordsResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_UpdateAnswerRecord : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_UpdateAnswerRecord() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::google::cloud::dialogflow::v2::UpdateAnswerRecordRequest, ::google::cloud::dialogflow::v2::AnswerRecord>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::google::cloud::dialogflow::v2::UpdateAnswerRecordRequest, ::google::cloud::dialogflow::v2::AnswerRecord>* streamer) {
                       return this->StreamedUpdateAnswerRecord(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_UpdateAnswerRecord() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status UpdateAnswerRecord(::grpc::ServerContext* /*context*/, const ::google::cloud::dialogflow::v2::UpdateAnswerRecordRequest* /*request*/, ::google::cloud::dialogflow::v2::AnswerRecord* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedUpdateAnswerRecord(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::google::cloud::dialogflow::v2::UpdateAnswerRecordRequest,::google::cloud::dialogflow::v2::AnswerRecord>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_ListAnswerRecords<WithStreamedUnaryMethod_UpdateAnswerRecord<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_ListAnswerRecords<WithStreamedUnaryMethod_UpdateAnswerRecord<Service > > StreamedService;
};

}  // namespace v2
}  // namespace dialogflow
}  // namespace cloud
}  // namespace google


#endif  // GRPC_google_2fcloud_2fdialogflow_2fv2_2fanswer_5frecord_2eproto__INCLUDED
