// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: google/cloud/dialogflow/v2/context.proto
// Original file comments:
// Copyright 2021 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#ifndef GRPC_google_2fcloud_2fdialogflow_2fv2_2fcontext_2eproto__INCLUDED
#define GRPC_google_2fcloud_2fdialogflow_2fv2_2fcontext_2eproto__INCLUDED

#include "google/cloud/dialogflow/v2/context.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace google {
namespace cloud {
namespace dialogflow {
namespace v2 {

// Service for managing [Contexts][google.cloud.dialogflow.v2.Context].
class Contexts final {
 public:
  static constexpr char const* service_full_name() {
    return "google.cloud.dialogflow.v2.Contexts";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Returns the list of all contexts in the specified session.
    virtual ::grpc::Status ListContexts(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::ListContextsRequest& request, ::google::cloud::dialogflow::v2::ListContextsResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2::ListContextsResponse>> AsyncListContexts(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::ListContextsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2::ListContextsResponse>>(AsyncListContextsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2::ListContextsResponse>> PrepareAsyncListContexts(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::ListContextsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2::ListContextsResponse>>(PrepareAsyncListContextsRaw(context, request, cq));
    }
    // Retrieves the specified context.
    virtual ::grpc::Status GetContext(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::GetContextRequest& request, ::google::cloud::dialogflow::v2::Context* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2::Context>> AsyncGetContext(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::GetContextRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2::Context>>(AsyncGetContextRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2::Context>> PrepareAsyncGetContext(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::GetContextRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2::Context>>(PrepareAsyncGetContextRaw(context, request, cq));
    }
    // Creates a context.
    //
    // If the specified context already exists, overrides the context.
    virtual ::grpc::Status CreateContext(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::CreateContextRequest& request, ::google::cloud::dialogflow::v2::Context* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2::Context>> AsyncCreateContext(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::CreateContextRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2::Context>>(AsyncCreateContextRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2::Context>> PrepareAsyncCreateContext(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::CreateContextRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2::Context>>(PrepareAsyncCreateContextRaw(context, request, cq));
    }
    // Updates the specified context.
    virtual ::grpc::Status UpdateContext(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::UpdateContextRequest& request, ::google::cloud::dialogflow::v2::Context* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2::Context>> AsyncUpdateContext(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::UpdateContextRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2::Context>>(AsyncUpdateContextRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2::Context>> PrepareAsyncUpdateContext(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::UpdateContextRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2::Context>>(PrepareAsyncUpdateContextRaw(context, request, cq));
    }
    // Deletes the specified context.
    virtual ::grpc::Status DeleteContext(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::DeleteContextRequest& request, ::google::protobuf::Empty* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>> AsyncDeleteContext(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::DeleteContextRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>>(AsyncDeleteContextRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>> PrepareAsyncDeleteContext(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::DeleteContextRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>>(PrepareAsyncDeleteContextRaw(context, request, cq));
    }
    // Deletes all active contexts in the specified session.
    virtual ::grpc::Status DeleteAllContexts(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::DeleteAllContextsRequest& request, ::google::protobuf::Empty* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>> AsyncDeleteAllContexts(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::DeleteAllContextsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>>(AsyncDeleteAllContextsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>> PrepareAsyncDeleteAllContexts(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::DeleteAllContextsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>>(PrepareAsyncDeleteAllContextsRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      // Returns the list of all contexts in the specified session.
      virtual void ListContexts(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::ListContextsRequest* request, ::google::cloud::dialogflow::v2::ListContextsResponse* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void ListContexts(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::ListContextsRequest* request, ::google::cloud::dialogflow::v2::ListContextsResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void ListContexts(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::ListContextsRequest* request, ::google::cloud::dialogflow::v2::ListContextsResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      // Retrieves the specified context.
      virtual void GetContext(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::GetContextRequest* request, ::google::cloud::dialogflow::v2::Context* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void GetContext(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::GetContextRequest* request, ::google::cloud::dialogflow::v2::Context* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void GetContext(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::GetContextRequest* request, ::google::cloud::dialogflow::v2::Context* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      // Creates a context.
      //
      // If the specified context already exists, overrides the context.
      virtual void CreateContext(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::CreateContextRequest* request, ::google::cloud::dialogflow::v2::Context* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void CreateContext(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::CreateContextRequest* request, ::google::cloud::dialogflow::v2::Context* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void CreateContext(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::CreateContextRequest* request, ::google::cloud::dialogflow::v2::Context* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      // Updates the specified context.
      virtual void UpdateContext(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::UpdateContextRequest* request, ::google::cloud::dialogflow::v2::Context* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void UpdateContext(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::UpdateContextRequest* request, ::google::cloud::dialogflow::v2::Context* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void UpdateContext(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::UpdateContextRequest* request, ::google::cloud::dialogflow::v2::Context* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      // Deletes the specified context.
      virtual void DeleteContext(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::DeleteContextRequest* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void DeleteContext(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::DeleteContextRequest* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void DeleteContext(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::DeleteContextRequest* request, ::google::protobuf::Empty* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      // Deletes all active contexts in the specified session.
      virtual void DeleteAllContexts(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::DeleteAllContextsRequest* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void DeleteAllContexts(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::DeleteAllContextsRequest* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void DeleteAllContexts(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::DeleteAllContextsRequest* request, ::google::protobuf::Empty* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2::ListContextsResponse>* AsyncListContextsRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::ListContextsRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2::ListContextsResponse>* PrepareAsyncListContextsRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::ListContextsRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2::Context>* AsyncGetContextRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::GetContextRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2::Context>* PrepareAsyncGetContextRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::GetContextRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2::Context>* AsyncCreateContextRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::CreateContextRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2::Context>* PrepareAsyncCreateContextRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::CreateContextRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2::Context>* AsyncUpdateContextRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::UpdateContextRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2::Context>* PrepareAsyncUpdateContextRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::UpdateContextRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>* AsyncDeleteContextRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::DeleteContextRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>* PrepareAsyncDeleteContextRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::DeleteContextRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>* AsyncDeleteAllContextsRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::DeleteAllContextsRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>* PrepareAsyncDeleteAllContextsRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::DeleteAllContextsRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status ListContexts(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::ListContextsRequest& request, ::google::cloud::dialogflow::v2::ListContextsResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2::ListContextsResponse>> AsyncListContexts(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::ListContextsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2::ListContextsResponse>>(AsyncListContextsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2::ListContextsResponse>> PrepareAsyncListContexts(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::ListContextsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2::ListContextsResponse>>(PrepareAsyncListContextsRaw(context, request, cq));
    }
    ::grpc::Status GetContext(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::GetContextRequest& request, ::google::cloud::dialogflow::v2::Context* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2::Context>> AsyncGetContext(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::GetContextRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2::Context>>(AsyncGetContextRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2::Context>> PrepareAsyncGetContext(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::GetContextRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2::Context>>(PrepareAsyncGetContextRaw(context, request, cq));
    }
    ::grpc::Status CreateContext(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::CreateContextRequest& request, ::google::cloud::dialogflow::v2::Context* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2::Context>> AsyncCreateContext(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::CreateContextRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2::Context>>(AsyncCreateContextRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2::Context>> PrepareAsyncCreateContext(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::CreateContextRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2::Context>>(PrepareAsyncCreateContextRaw(context, request, cq));
    }
    ::grpc::Status UpdateContext(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::UpdateContextRequest& request, ::google::cloud::dialogflow::v2::Context* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2::Context>> AsyncUpdateContext(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::UpdateContextRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2::Context>>(AsyncUpdateContextRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2::Context>> PrepareAsyncUpdateContext(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::UpdateContextRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2::Context>>(PrepareAsyncUpdateContextRaw(context, request, cq));
    }
    ::grpc::Status DeleteContext(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::DeleteContextRequest& request, ::google::protobuf::Empty* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>> AsyncDeleteContext(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::DeleteContextRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>>(AsyncDeleteContextRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>> PrepareAsyncDeleteContext(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::DeleteContextRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>>(PrepareAsyncDeleteContextRaw(context, request, cq));
    }
    ::grpc::Status DeleteAllContexts(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::DeleteAllContextsRequest& request, ::google::protobuf::Empty* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>> AsyncDeleteAllContexts(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::DeleteAllContextsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>>(AsyncDeleteAllContextsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>> PrepareAsyncDeleteAllContexts(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::DeleteAllContextsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>>(PrepareAsyncDeleteAllContextsRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void ListContexts(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::ListContextsRequest* request, ::google::cloud::dialogflow::v2::ListContextsResponse* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void ListContexts(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::ListContextsRequest* request, ::google::cloud::dialogflow::v2::ListContextsResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void ListContexts(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::ListContextsRequest* request, ::google::cloud::dialogflow::v2::ListContextsResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      void GetContext(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::GetContextRequest* request, ::google::cloud::dialogflow::v2::Context* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void GetContext(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::GetContextRequest* request, ::google::cloud::dialogflow::v2::Context* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void GetContext(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::GetContextRequest* request, ::google::cloud::dialogflow::v2::Context* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      void CreateContext(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::CreateContextRequest* request, ::google::cloud::dialogflow::v2::Context* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void CreateContext(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::CreateContextRequest* request, ::google::cloud::dialogflow::v2::Context* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void CreateContext(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::CreateContextRequest* request, ::google::cloud::dialogflow::v2::Context* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      void UpdateContext(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::UpdateContextRequest* request, ::google::cloud::dialogflow::v2::Context* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void UpdateContext(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::UpdateContextRequest* request, ::google::cloud::dialogflow::v2::Context* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void UpdateContext(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::UpdateContextRequest* request, ::google::cloud::dialogflow::v2::Context* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      void DeleteContext(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::DeleteContextRequest* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void DeleteContext(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::DeleteContextRequest* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void DeleteContext(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::DeleteContextRequest* request, ::google::protobuf::Empty* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      void DeleteAllContexts(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::DeleteAllContextsRequest* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void DeleteAllContexts(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::DeleteAllContextsRequest* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void DeleteAllContexts(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::DeleteAllContextsRequest* request, ::google::protobuf::Empty* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2::ListContextsResponse>* AsyncListContextsRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::ListContextsRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2::ListContextsResponse>* PrepareAsyncListContextsRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::ListContextsRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2::Context>* AsyncGetContextRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::GetContextRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2::Context>* PrepareAsyncGetContextRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::GetContextRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2::Context>* AsyncCreateContextRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::CreateContextRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2::Context>* PrepareAsyncCreateContextRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::CreateContextRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2::Context>* AsyncUpdateContextRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::UpdateContextRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2::Context>* PrepareAsyncUpdateContextRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::UpdateContextRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* AsyncDeleteContextRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::DeleteContextRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* PrepareAsyncDeleteContextRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::DeleteContextRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* AsyncDeleteAllContextsRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::DeleteAllContextsRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* PrepareAsyncDeleteAllContextsRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::DeleteAllContextsRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_ListContexts_;
    const ::grpc::internal::RpcMethod rpcmethod_GetContext_;
    const ::grpc::internal::RpcMethod rpcmethod_CreateContext_;
    const ::grpc::internal::RpcMethod rpcmethod_UpdateContext_;
    const ::grpc::internal::RpcMethod rpcmethod_DeleteContext_;
    const ::grpc::internal::RpcMethod rpcmethod_DeleteAllContexts_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Returns the list of all contexts in the specified session.
    virtual ::grpc::Status ListContexts(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2::ListContextsRequest* request, ::google::cloud::dialogflow::v2::ListContextsResponse* response);
    // Retrieves the specified context.
    virtual ::grpc::Status GetContext(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2::GetContextRequest* request, ::google::cloud::dialogflow::v2::Context* response);
    // Creates a context.
    //
    // If the specified context already exists, overrides the context.
    virtual ::grpc::Status CreateContext(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2::CreateContextRequest* request, ::google::cloud::dialogflow::v2::Context* response);
    // Updates the specified context.
    virtual ::grpc::Status UpdateContext(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2::UpdateContextRequest* request, ::google::cloud::dialogflow::v2::Context* response);
    // Deletes the specified context.
    virtual ::grpc::Status DeleteContext(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2::DeleteContextRequest* request, ::google::protobuf::Empty* response);
    // Deletes all active contexts in the specified session.
    virtual ::grpc::Status DeleteAllContexts(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2::DeleteAllContextsRequest* request, ::google::protobuf::Empty* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_ListContexts : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ListContexts() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_ListContexts() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListContexts(::grpc::ServerContext* /*context*/, const ::google::cloud::dialogflow::v2::ListContextsRequest* /*request*/, ::google::cloud::dialogflow::v2::ListContextsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestListContexts(::grpc::ServerContext* context, ::google::cloud::dialogflow::v2::ListContextsRequest* request, ::grpc::ServerAsyncResponseWriter< ::google::cloud::dialogflow::v2::ListContextsResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetContext : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetContext() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_GetContext() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetContext(::grpc::ServerContext* /*context*/, const ::google::cloud::dialogflow::v2::GetContextRequest* /*request*/, ::google::cloud::dialogflow::v2::Context* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetContext(::grpc::ServerContext* context, ::google::cloud::dialogflow::v2::GetContextRequest* request, ::grpc::ServerAsyncResponseWriter< ::google::cloud::dialogflow::v2::Context>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_CreateContext : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_CreateContext() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_CreateContext() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateContext(::grpc::ServerContext* /*context*/, const ::google::cloud::dialogflow::v2::CreateContextRequest* /*request*/, ::google::cloud::dialogflow::v2::Context* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCreateContext(::grpc::ServerContext* context, ::google::cloud::dialogflow::v2::CreateContextRequest* request, ::grpc::ServerAsyncResponseWriter< ::google::cloud::dialogflow::v2::Context>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_UpdateContext : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_UpdateContext() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_UpdateContext() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateContext(::grpc::ServerContext* /*context*/, const ::google::cloud::dialogflow::v2::UpdateContextRequest* /*request*/, ::google::cloud::dialogflow::v2::Context* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestUpdateContext(::grpc::ServerContext* context, ::google::cloud::dialogflow::v2::UpdateContextRequest* request, ::grpc::ServerAsyncResponseWriter< ::google::cloud::dialogflow::v2::Context>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_DeleteContext : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_DeleteContext() {
      ::grpc::Service::MarkMethodAsync(4);
    }
    ~WithAsyncMethod_DeleteContext() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeleteContext(::grpc::ServerContext* /*context*/, const ::google::cloud::dialogflow::v2::DeleteContextRequest* /*request*/, ::google::protobuf::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDeleteContext(::grpc::ServerContext* context, ::google::cloud::dialogflow::v2::DeleteContextRequest* request, ::grpc::ServerAsyncResponseWriter< ::google::protobuf::Empty>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_DeleteAllContexts : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_DeleteAllContexts() {
      ::grpc::Service::MarkMethodAsync(5);
    }
    ~WithAsyncMethod_DeleteAllContexts() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeleteAllContexts(::grpc::ServerContext* /*context*/, const ::google::cloud::dialogflow::v2::DeleteAllContextsRequest* /*request*/, ::google::protobuf::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDeleteAllContexts(::grpc::ServerContext* context, ::google::cloud::dialogflow::v2::DeleteAllContextsRequest* request, ::grpc::ServerAsyncResponseWriter< ::google::protobuf::Empty>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(5, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_ListContexts<WithAsyncMethod_GetContext<WithAsyncMethod_CreateContext<WithAsyncMethod_UpdateContext<WithAsyncMethod_DeleteContext<WithAsyncMethod_DeleteAllContexts<Service > > > > > > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_ListContexts : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_ListContexts() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::google::cloud::dialogflow::v2::ListContextsRequest, ::google::cloud::dialogflow::v2::ListContextsResponse>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::google::cloud::dialogflow::v2::ListContextsRequest* request, ::google::cloud::dialogflow::v2::ListContextsResponse* response) { return this->ListContexts(context, request, response); }));}
    void SetMessageAllocatorFor_ListContexts(
        ::grpc::experimental::MessageAllocator< ::google::cloud::dialogflow::v2::ListContextsRequest, ::google::cloud::dialogflow::v2::ListContextsResponse>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::google::cloud::dialogflow::v2::ListContextsRequest, ::google::cloud::dialogflow::v2::ListContextsResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_ListContexts() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListContexts(::grpc::ServerContext* /*context*/, const ::google::cloud::dialogflow::v2::ListContextsRequest* /*request*/, ::google::cloud::dialogflow::v2::ListContextsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* ListContexts(
      ::grpc::CallbackServerContext* /*context*/, const ::google::cloud::dialogflow::v2::ListContextsRequest* /*request*/, ::google::cloud::dialogflow::v2::ListContextsResponse* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* ListContexts(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::google::cloud::dialogflow::v2::ListContextsRequest* /*request*/, ::google::cloud::dialogflow::v2::ListContextsResponse* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_GetContext : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_GetContext() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::google::cloud::dialogflow::v2::GetContextRequest, ::google::cloud::dialogflow::v2::Context>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::google::cloud::dialogflow::v2::GetContextRequest* request, ::google::cloud::dialogflow::v2::Context* response) { return this->GetContext(context, request, response); }));}
    void SetMessageAllocatorFor_GetContext(
        ::grpc::experimental::MessageAllocator< ::google::cloud::dialogflow::v2::GetContextRequest, ::google::cloud::dialogflow::v2::Context>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(1);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::google::cloud::dialogflow::v2::GetContextRequest, ::google::cloud::dialogflow::v2::Context>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_GetContext() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetContext(::grpc::ServerContext* /*context*/, const ::google::cloud::dialogflow::v2::GetContextRequest* /*request*/, ::google::cloud::dialogflow::v2::Context* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* GetContext(
      ::grpc::CallbackServerContext* /*context*/, const ::google::cloud::dialogflow::v2::GetContextRequest* /*request*/, ::google::cloud::dialogflow::v2::Context* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* GetContext(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::google::cloud::dialogflow::v2::GetContextRequest* /*request*/, ::google::cloud::dialogflow::v2::Context* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_CreateContext : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_CreateContext() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::google::cloud::dialogflow::v2::CreateContextRequest, ::google::cloud::dialogflow::v2::Context>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::google::cloud::dialogflow::v2::CreateContextRequest* request, ::google::cloud::dialogflow::v2::Context* response) { return this->CreateContext(context, request, response); }));}
    void SetMessageAllocatorFor_CreateContext(
        ::grpc::experimental::MessageAllocator< ::google::cloud::dialogflow::v2::CreateContextRequest, ::google::cloud::dialogflow::v2::Context>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(2);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::google::cloud::dialogflow::v2::CreateContextRequest, ::google::cloud::dialogflow::v2::Context>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_CreateContext() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateContext(::grpc::ServerContext* /*context*/, const ::google::cloud::dialogflow::v2::CreateContextRequest* /*request*/, ::google::cloud::dialogflow::v2::Context* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* CreateContext(
      ::grpc::CallbackServerContext* /*context*/, const ::google::cloud::dialogflow::v2::CreateContextRequest* /*request*/, ::google::cloud::dialogflow::v2::Context* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* CreateContext(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::google::cloud::dialogflow::v2::CreateContextRequest* /*request*/, ::google::cloud::dialogflow::v2::Context* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_UpdateContext : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_UpdateContext() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::google::cloud::dialogflow::v2::UpdateContextRequest, ::google::cloud::dialogflow::v2::Context>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::google::cloud::dialogflow::v2::UpdateContextRequest* request, ::google::cloud::dialogflow::v2::Context* response) { return this->UpdateContext(context, request, response); }));}
    void SetMessageAllocatorFor_UpdateContext(
        ::grpc::experimental::MessageAllocator< ::google::cloud::dialogflow::v2::UpdateContextRequest, ::google::cloud::dialogflow::v2::Context>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(3);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(3);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::google::cloud::dialogflow::v2::UpdateContextRequest, ::google::cloud::dialogflow::v2::Context>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_UpdateContext() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateContext(::grpc::ServerContext* /*context*/, const ::google::cloud::dialogflow::v2::UpdateContextRequest* /*request*/, ::google::cloud::dialogflow::v2::Context* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* UpdateContext(
      ::grpc::CallbackServerContext* /*context*/, const ::google::cloud::dialogflow::v2::UpdateContextRequest* /*request*/, ::google::cloud::dialogflow::v2::Context* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* UpdateContext(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::google::cloud::dialogflow::v2::UpdateContextRequest* /*request*/, ::google::cloud::dialogflow::v2::Context* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_DeleteContext : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_DeleteContext() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::google::cloud::dialogflow::v2::DeleteContextRequest, ::google::protobuf::Empty>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::google::cloud::dialogflow::v2::DeleteContextRequest* request, ::google::protobuf::Empty* response) { return this->DeleteContext(context, request, response); }));}
    void SetMessageAllocatorFor_DeleteContext(
        ::grpc::experimental::MessageAllocator< ::google::cloud::dialogflow::v2::DeleteContextRequest, ::google::protobuf::Empty>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(4);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(4);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::google::cloud::dialogflow::v2::DeleteContextRequest, ::google::protobuf::Empty>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_DeleteContext() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeleteContext(::grpc::ServerContext* /*context*/, const ::google::cloud::dialogflow::v2::DeleteContextRequest* /*request*/, ::google::protobuf::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* DeleteContext(
      ::grpc::CallbackServerContext* /*context*/, const ::google::cloud::dialogflow::v2::DeleteContextRequest* /*request*/, ::google::protobuf::Empty* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* DeleteContext(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::google::cloud::dialogflow::v2::DeleteContextRequest* /*request*/, ::google::protobuf::Empty* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_DeleteAllContexts : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_DeleteAllContexts() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(5,
          new ::grpc::internal::CallbackUnaryHandler< ::google::cloud::dialogflow::v2::DeleteAllContextsRequest, ::google::protobuf::Empty>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::google::cloud::dialogflow::v2::DeleteAllContextsRequest* request, ::google::protobuf::Empty* response) { return this->DeleteAllContexts(context, request, response); }));}
    void SetMessageAllocatorFor_DeleteAllContexts(
        ::grpc::experimental::MessageAllocator< ::google::cloud::dialogflow::v2::DeleteAllContextsRequest, ::google::protobuf::Empty>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(5);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(5);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::google::cloud::dialogflow::v2::DeleteAllContextsRequest, ::google::protobuf::Empty>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_DeleteAllContexts() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeleteAllContexts(::grpc::ServerContext* /*context*/, const ::google::cloud::dialogflow::v2::DeleteAllContextsRequest* /*request*/, ::google::protobuf::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* DeleteAllContexts(
      ::grpc::CallbackServerContext* /*context*/, const ::google::cloud::dialogflow::v2::DeleteAllContextsRequest* /*request*/, ::google::protobuf::Empty* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* DeleteAllContexts(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::google::cloud::dialogflow::v2::DeleteAllContextsRequest* /*request*/, ::google::protobuf::Empty* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_ListContexts<ExperimentalWithCallbackMethod_GetContext<ExperimentalWithCallbackMethod_CreateContext<ExperimentalWithCallbackMethod_UpdateContext<ExperimentalWithCallbackMethod_DeleteContext<ExperimentalWithCallbackMethod_DeleteAllContexts<Service > > > > > > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_ListContexts<ExperimentalWithCallbackMethod_GetContext<ExperimentalWithCallbackMethod_CreateContext<ExperimentalWithCallbackMethod_UpdateContext<ExperimentalWithCallbackMethod_DeleteContext<ExperimentalWithCallbackMethod_DeleteAllContexts<Service > > > > > > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_ListContexts : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ListContexts() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_ListContexts() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListContexts(::grpc::ServerContext* /*context*/, const ::google::cloud::dialogflow::v2::ListContextsRequest* /*request*/, ::google::cloud::dialogflow::v2::ListContextsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetContext : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetContext() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_GetContext() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetContext(::grpc::ServerContext* /*context*/, const ::google::cloud::dialogflow::v2::GetContextRequest* /*request*/, ::google::cloud::dialogflow::v2::Context* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_CreateContext : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_CreateContext() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_CreateContext() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateContext(::grpc::ServerContext* /*context*/, const ::google::cloud::dialogflow::v2::CreateContextRequest* /*request*/, ::google::cloud::dialogflow::v2::Context* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_UpdateContext : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_UpdateContext() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_UpdateContext() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateContext(::grpc::ServerContext* /*context*/, const ::google::cloud::dialogflow::v2::UpdateContextRequest* /*request*/, ::google::cloud::dialogflow::v2::Context* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_DeleteContext : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_DeleteContext() {
      ::grpc::Service::MarkMethodGeneric(4);
    }
    ~WithGenericMethod_DeleteContext() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeleteContext(::grpc::ServerContext* /*context*/, const ::google::cloud::dialogflow::v2::DeleteContextRequest* /*request*/, ::google::protobuf::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_DeleteAllContexts : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_DeleteAllContexts() {
      ::grpc::Service::MarkMethodGeneric(5);
    }
    ~WithGenericMethod_DeleteAllContexts() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeleteAllContexts(::grpc::ServerContext* /*context*/, const ::google::cloud::dialogflow::v2::DeleteAllContextsRequest* /*request*/, ::google::protobuf::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_ListContexts : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ListContexts() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_ListContexts() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListContexts(::grpc::ServerContext* /*context*/, const ::google::cloud::dialogflow::v2::ListContextsRequest* /*request*/, ::google::cloud::dialogflow::v2::ListContextsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestListContexts(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetContext : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetContext() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_GetContext() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetContext(::grpc::ServerContext* /*context*/, const ::google::cloud::dialogflow::v2::GetContextRequest* /*request*/, ::google::cloud::dialogflow::v2::Context* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetContext(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_CreateContext : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_CreateContext() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_CreateContext() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateContext(::grpc::ServerContext* /*context*/, const ::google::cloud::dialogflow::v2::CreateContextRequest* /*request*/, ::google::cloud::dialogflow::v2::Context* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCreateContext(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_UpdateContext : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_UpdateContext() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_UpdateContext() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateContext(::grpc::ServerContext* /*context*/, const ::google::cloud::dialogflow::v2::UpdateContextRequest* /*request*/, ::google::cloud::dialogflow::v2::Context* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestUpdateContext(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_DeleteContext : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_DeleteContext() {
      ::grpc::Service::MarkMethodRaw(4);
    }
    ~WithRawMethod_DeleteContext() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeleteContext(::grpc::ServerContext* /*context*/, const ::google::cloud::dialogflow::v2::DeleteContextRequest* /*request*/, ::google::protobuf::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDeleteContext(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_DeleteAllContexts : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_DeleteAllContexts() {
      ::grpc::Service::MarkMethodRaw(5);
    }
    ~WithRawMethod_DeleteAllContexts() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeleteAllContexts(::grpc::ServerContext* /*context*/, const ::google::cloud::dialogflow::v2::DeleteAllContextsRequest* /*request*/, ::google::protobuf::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDeleteAllContexts(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(5, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_ListContexts : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_ListContexts() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ListContexts(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_ListContexts() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListContexts(::grpc::ServerContext* /*context*/, const ::google::cloud::dialogflow::v2::ListContextsRequest* /*request*/, ::google::cloud::dialogflow::v2::ListContextsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* ListContexts(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* ListContexts(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_GetContext : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_GetContext() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetContext(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_GetContext() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetContext(::grpc::ServerContext* /*context*/, const ::google::cloud::dialogflow::v2::GetContextRequest* /*request*/, ::google::cloud::dialogflow::v2::Context* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* GetContext(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* GetContext(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_CreateContext : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_CreateContext() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->CreateContext(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_CreateContext() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateContext(::grpc::ServerContext* /*context*/, const ::google::cloud::dialogflow::v2::CreateContextRequest* /*request*/, ::google::cloud::dialogflow::v2::Context* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* CreateContext(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* CreateContext(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_UpdateContext : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_UpdateContext() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->UpdateContext(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_UpdateContext() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateContext(::grpc::ServerContext* /*context*/, const ::google::cloud::dialogflow::v2::UpdateContextRequest* /*request*/, ::google::cloud::dialogflow::v2::Context* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* UpdateContext(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* UpdateContext(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_DeleteContext : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_DeleteContext() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->DeleteContext(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_DeleteContext() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeleteContext(::grpc::ServerContext* /*context*/, const ::google::cloud::dialogflow::v2::DeleteContextRequest* /*request*/, ::google::protobuf::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* DeleteContext(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* DeleteContext(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_DeleteAllContexts : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_DeleteAllContexts() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(5,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->DeleteAllContexts(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_DeleteAllContexts() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeleteAllContexts(::grpc::ServerContext* /*context*/, const ::google::cloud::dialogflow::v2::DeleteAllContextsRequest* /*request*/, ::google::protobuf::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* DeleteAllContexts(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* DeleteAllContexts(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ListContexts : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ListContexts() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::google::cloud::dialogflow::v2::ListContextsRequest, ::google::cloud::dialogflow::v2::ListContextsResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::google::cloud::dialogflow::v2::ListContextsRequest, ::google::cloud::dialogflow::v2::ListContextsResponse>* streamer) {
                       return this->StreamedListContexts(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ListContexts() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ListContexts(::grpc::ServerContext* /*context*/, const ::google::cloud::dialogflow::v2::ListContextsRequest* /*request*/, ::google::cloud::dialogflow::v2::ListContextsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedListContexts(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::google::cloud::dialogflow::v2::ListContextsRequest,::google::cloud::dialogflow::v2::ListContextsResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetContext : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetContext() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::google::cloud::dialogflow::v2::GetContextRequest, ::google::cloud::dialogflow::v2::Context>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::google::cloud::dialogflow::v2::GetContextRequest, ::google::cloud::dialogflow::v2::Context>* streamer) {
                       return this->StreamedGetContext(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetContext() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetContext(::grpc::ServerContext* /*context*/, const ::google::cloud::dialogflow::v2::GetContextRequest* /*request*/, ::google::cloud::dialogflow::v2::Context* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetContext(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::google::cloud::dialogflow::v2::GetContextRequest,::google::cloud::dialogflow::v2::Context>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_CreateContext : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_CreateContext() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::google::cloud::dialogflow::v2::CreateContextRequest, ::google::cloud::dialogflow::v2::Context>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::google::cloud::dialogflow::v2::CreateContextRequest, ::google::cloud::dialogflow::v2::Context>* streamer) {
                       return this->StreamedCreateContext(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_CreateContext() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status CreateContext(::grpc::ServerContext* /*context*/, const ::google::cloud::dialogflow::v2::CreateContextRequest* /*request*/, ::google::cloud::dialogflow::v2::Context* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedCreateContext(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::google::cloud::dialogflow::v2::CreateContextRequest,::google::cloud::dialogflow::v2::Context>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_UpdateContext : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_UpdateContext() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler<
          ::google::cloud::dialogflow::v2::UpdateContextRequest, ::google::cloud::dialogflow::v2::Context>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::google::cloud::dialogflow::v2::UpdateContextRequest, ::google::cloud::dialogflow::v2::Context>* streamer) {
                       return this->StreamedUpdateContext(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_UpdateContext() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status UpdateContext(::grpc::ServerContext* /*context*/, const ::google::cloud::dialogflow::v2::UpdateContextRequest* /*request*/, ::google::cloud::dialogflow::v2::Context* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedUpdateContext(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::google::cloud::dialogflow::v2::UpdateContextRequest,::google::cloud::dialogflow::v2::Context>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_DeleteContext : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_DeleteContext() {
      ::grpc::Service::MarkMethodStreamed(4,
        new ::grpc::internal::StreamedUnaryHandler<
          ::google::cloud::dialogflow::v2::DeleteContextRequest, ::google::protobuf::Empty>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::google::cloud::dialogflow::v2::DeleteContextRequest, ::google::protobuf::Empty>* streamer) {
                       return this->StreamedDeleteContext(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_DeleteContext() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status DeleteContext(::grpc::ServerContext* /*context*/, const ::google::cloud::dialogflow::v2::DeleteContextRequest* /*request*/, ::google::protobuf::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedDeleteContext(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::google::cloud::dialogflow::v2::DeleteContextRequest,::google::protobuf::Empty>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_DeleteAllContexts : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_DeleteAllContexts() {
      ::grpc::Service::MarkMethodStreamed(5,
        new ::grpc::internal::StreamedUnaryHandler<
          ::google::cloud::dialogflow::v2::DeleteAllContextsRequest, ::google::protobuf::Empty>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::google::cloud::dialogflow::v2::DeleteAllContextsRequest, ::google::protobuf::Empty>* streamer) {
                       return this->StreamedDeleteAllContexts(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_DeleteAllContexts() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status DeleteAllContexts(::grpc::ServerContext* /*context*/, const ::google::cloud::dialogflow::v2::DeleteAllContextsRequest* /*request*/, ::google::protobuf::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedDeleteAllContexts(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::google::cloud::dialogflow::v2::DeleteAllContextsRequest,::google::protobuf::Empty>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_ListContexts<WithStreamedUnaryMethod_GetContext<WithStreamedUnaryMethod_CreateContext<WithStreamedUnaryMethod_UpdateContext<WithStreamedUnaryMethod_DeleteContext<WithStreamedUnaryMethod_DeleteAllContexts<Service > > > > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_ListContexts<WithStreamedUnaryMethod_GetContext<WithStreamedUnaryMethod_CreateContext<WithStreamedUnaryMethod_UpdateContext<WithStreamedUnaryMethod_DeleteContext<WithStreamedUnaryMethod_DeleteAllContexts<Service > > > > > > StreamedService;
};

}  // namespace v2
}  // namespace dialogflow
}  // namespace cloud
}  // namespace google


#endif  // GRPC_google_2fcloud_2fdialogflow_2fv2_2fcontext_2eproto__INCLUDED
