// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/monitoring/v3/mutation_record.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_google_2fmonitoring_2fv3_2fmutation_5frecord_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_google_2fmonitoring_2fv3_2fmutation_5frecord_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021011 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/timestamp.pb.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_google_2fmonitoring_2fv3_2fmutation_5frecord_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_google_2fmonitoring_2fv3_2fmutation_5frecord_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_google_2fmonitoring_2fv3_2fmutation_5frecord_2eproto;
namespace google {
namespace monitoring {
namespace v3 {
class MutationRecord;
struct MutationRecordDefaultTypeInternal;
extern MutationRecordDefaultTypeInternal _MutationRecord_default_instance_;
}  // namespace v3
}  // namespace monitoring
}  // namespace google
PROTOBUF_NAMESPACE_OPEN
template<> ::google::monitoring::v3::MutationRecord* Arena::CreateMaybeMessage<::google::monitoring::v3::MutationRecord>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace google {
namespace monitoring {
namespace v3 {

// ===================================================================

class MutationRecord final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:google.monitoring.v3.MutationRecord) */ {
 public:
  inline MutationRecord() : MutationRecord(nullptr) {}
  ~MutationRecord() override;
  explicit PROTOBUF_CONSTEXPR MutationRecord(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  MutationRecord(const MutationRecord& from);
  MutationRecord(MutationRecord&& from) noexcept
    : MutationRecord() {
    *this = ::std::move(from);
  }

  inline MutationRecord& operator=(const MutationRecord& from) {
    CopyFrom(from);
    return *this;
  }
  inline MutationRecord& operator=(MutationRecord&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MutationRecord& default_instance() {
    return *internal_default_instance();
  }
  static inline const MutationRecord* internal_default_instance() {
    return reinterpret_cast<const MutationRecord*>(
               &_MutationRecord_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(MutationRecord& a, MutationRecord& b) {
    a.Swap(&b);
  }
  inline void Swap(MutationRecord* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MutationRecord* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MutationRecord* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<MutationRecord>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const MutationRecord& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const MutationRecord& from) {
    MutationRecord::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MutationRecord* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "google.monitoring.v3.MutationRecord";
  }
  protected:
  explicit MutationRecord(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMutatedByFieldNumber = 2,
    kMutateTimeFieldNumber = 1,
  };
  // string mutated_by = 2;
  void clear_mutated_by();
  const std::string& mutated_by() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_mutated_by(ArgT0&& arg0, ArgT... args);
  std::string* mutable_mutated_by();
  PROTOBUF_NODISCARD std::string* release_mutated_by();
  void set_allocated_mutated_by(std::string* mutated_by);
  private:
  const std::string& _internal_mutated_by() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_mutated_by(const std::string& value);
  std::string* _internal_mutable_mutated_by();
  public:

  // .google.protobuf.Timestamp mutate_time = 1;
  bool has_mutate_time() const;
  private:
  bool _internal_has_mutate_time() const;
  public:
  void clear_mutate_time();
  const ::PROTOBUF_NAMESPACE_ID::Timestamp& mutate_time() const;
  PROTOBUF_NODISCARD ::PROTOBUF_NAMESPACE_ID::Timestamp* release_mutate_time();
  ::PROTOBUF_NAMESPACE_ID::Timestamp* mutable_mutate_time();
  void set_allocated_mutate_time(::PROTOBUF_NAMESPACE_ID::Timestamp* mutate_time);
  private:
  const ::PROTOBUF_NAMESPACE_ID::Timestamp& _internal_mutate_time() const;
  ::PROTOBUF_NAMESPACE_ID::Timestamp* _internal_mutable_mutate_time();
  public:
  void unsafe_arena_set_allocated_mutate_time(
      ::PROTOBUF_NAMESPACE_ID::Timestamp* mutate_time);
  ::PROTOBUF_NAMESPACE_ID::Timestamp* unsafe_arena_release_mutate_time();

  // @@protoc_insertion_point(class_scope:google.monitoring.v3.MutationRecord)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr mutated_by_;
    ::PROTOBUF_NAMESPACE_ID::Timestamp* mutate_time_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_google_2fmonitoring_2fv3_2fmutation_5frecord_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// MutationRecord

// .google.protobuf.Timestamp mutate_time = 1;
inline bool MutationRecord::_internal_has_mutate_time() const {
  return this != internal_default_instance() && _impl_.mutate_time_ != nullptr;
}
inline bool MutationRecord::has_mutate_time() const {
  return _internal_has_mutate_time();
}
inline const ::PROTOBUF_NAMESPACE_ID::Timestamp& MutationRecord::_internal_mutate_time() const {
  const ::PROTOBUF_NAMESPACE_ID::Timestamp* p = _impl_.mutate_time_;
  return p != nullptr ? *p : reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Timestamp&>(
      ::PROTOBUF_NAMESPACE_ID::_Timestamp_default_instance_);
}
inline const ::PROTOBUF_NAMESPACE_ID::Timestamp& MutationRecord::mutate_time() const {
  // @@protoc_insertion_point(field_get:google.monitoring.v3.MutationRecord.mutate_time)
  return _internal_mutate_time();
}
inline void MutationRecord::unsafe_arena_set_allocated_mutate_time(
    ::PROTOBUF_NAMESPACE_ID::Timestamp* mutate_time) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.mutate_time_);
  }
  _impl_.mutate_time_ = mutate_time;
  if (mutate_time) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:google.monitoring.v3.MutationRecord.mutate_time)
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* MutationRecord::release_mutate_time() {
  
  ::PROTOBUF_NAMESPACE_ID::Timestamp* temp = _impl_.mutate_time_;
  _impl_.mutate_time_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* MutationRecord::unsafe_arena_release_mutate_time() {
  // @@protoc_insertion_point(field_release:google.monitoring.v3.MutationRecord.mutate_time)
  
  ::PROTOBUF_NAMESPACE_ID::Timestamp* temp = _impl_.mutate_time_;
  _impl_.mutate_time_ = nullptr;
  return temp;
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* MutationRecord::_internal_mutable_mutate_time() {
  
  if (_impl_.mutate_time_ == nullptr) {
    auto* p = CreateMaybeMessage<::PROTOBUF_NAMESPACE_ID::Timestamp>(GetArenaForAllocation());
    _impl_.mutate_time_ = p;
  }
  return _impl_.mutate_time_;
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* MutationRecord::mutable_mutate_time() {
  ::PROTOBUF_NAMESPACE_ID::Timestamp* _msg = _internal_mutable_mutate_time();
  // @@protoc_insertion_point(field_mutable:google.monitoring.v3.MutationRecord.mutate_time)
  return _msg;
}
inline void MutationRecord::set_allocated_mutate_time(::PROTOBUF_NAMESPACE_ID::Timestamp* mutate_time) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.mutate_time_);
  }
  if (mutate_time) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(mutate_time));
    if (message_arena != submessage_arena) {
      mutate_time = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, mutate_time, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.mutate_time_ = mutate_time;
  // @@protoc_insertion_point(field_set_allocated:google.monitoring.v3.MutationRecord.mutate_time)
}

// string mutated_by = 2;
inline void MutationRecord::clear_mutated_by() {
  _impl_.mutated_by_.ClearToEmpty();
}
inline const std::string& MutationRecord::mutated_by() const {
  // @@protoc_insertion_point(field_get:google.monitoring.v3.MutationRecord.mutated_by)
  return _internal_mutated_by();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void MutationRecord::set_mutated_by(ArgT0&& arg0, ArgT... args) {
 
 _impl_.mutated_by_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:google.monitoring.v3.MutationRecord.mutated_by)
}
inline std::string* MutationRecord::mutable_mutated_by() {
  std::string* _s = _internal_mutable_mutated_by();
  // @@protoc_insertion_point(field_mutable:google.monitoring.v3.MutationRecord.mutated_by)
  return _s;
}
inline const std::string& MutationRecord::_internal_mutated_by() const {
  return _impl_.mutated_by_.Get();
}
inline void MutationRecord::_internal_set_mutated_by(const std::string& value) {
  
  _impl_.mutated_by_.Set(value, GetArenaForAllocation());
}
inline std::string* MutationRecord::_internal_mutable_mutated_by() {
  
  return _impl_.mutated_by_.Mutable(GetArenaForAllocation());
}
inline std::string* MutationRecord::release_mutated_by() {
  // @@protoc_insertion_point(field_release:google.monitoring.v3.MutationRecord.mutated_by)
  return _impl_.mutated_by_.Release();
}
inline void MutationRecord::set_allocated_mutated_by(std::string* mutated_by) {
  if (mutated_by != nullptr) {
    
  } else {
    
  }
  _impl_.mutated_by_.SetAllocated(mutated_by, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.mutated_by_.IsDefault()) {
    _impl_.mutated_by_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:google.monitoring.v3.MutationRecord.mutated_by)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace v3
}  // namespace monitoring
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_google_2fmonitoring_2fv3_2fmutation_5frecord_2eproto
